---
name: Release
on: [create]
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Create release
        run: gh release create "$GITHUB_REF_NAME" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Calculate SHA256
        run: sha256sum quaternion2matrix > quaternion2matrix.sha256sum
      - name: Upload artifacts
        run: gh release upload "$GITHUB_REF_NAME" quaternion2matrix quaternion2matrix.sha256sum
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
